<?php

/**
 * BaseOportunityTaksConfiguration
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $time_between_emails
 * @property integer $simultanious_mails
 * 
 * @method integer                     getId()                  Returns the current record's "id" value
 * @method integer                     getTimeBetweenEmails()   Returns the current record's "time_between_emails" value
 * @method integer                     getSimultaniousMails()   Returns the current record's "simultanious_mails" value
 * @method OportunityTaksConfiguration setId()                  Sets the current record's "id" value
 * @method OportunityTaksConfiguration setTimeBetweenEmails()   Sets the current record's "time_between_emails" value
 * @method OportunityTaksConfiguration setSimultaniousMails()   Sets the current record's "simultanious_mails" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOportunityTaksConfiguration extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('OportunityTaksConfiguration');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('time_between_emails', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('simultanious_mails', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}