<?php


/**
 * BaseComunas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigo
 * @property string $nombre
 * @property Doctrine_Collection $Regiones
 * 
 * @method integer             getCodigo()        Returns the current record's "codigo" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method Doctrine_Collection getComunas()     Returns the current record's "Comunas" collection


 * @method Regiones              setRegiones()                 Sets the current record's "Regiones" collection
 * 
 * @package    RegionesSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegiones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Regiones');
        $this->hasColumn('codigo', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }
    
    public function setUp()
    {
        parent::setUp();

        $this->hasMany('Comuna as Comunas', array(
             'local' => 'id',
             'foreign' => 'Padre'));
    }
}