<?php

/**
 * BaseCarType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string  $name
 * 
 * @method integer         getId()         Returns the current record's "id" value
 * @method string          getName()       Returns the current record's "name" value
 * @method CarType         setId()         Sets the current record's "id" value
 * @method CarType         setName()       Sets the current record's "name" value
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CarType');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();

        $this->hasMany('Model as Models', array(
             'local' => 'id',
             'foreign' => 'id_otro_tipo_vehiculo'));
    }
}