<?php

/**
 * BaseHoliday
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property date $date
 * @property string $name
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method date                getDate()           Returns the current record's "date" value
 * @method string              getName()           Returns the current record's "name" value
 * 
 * @method Holiday             setId()             Sets the current record's "id" value
 * @method Holiday             setDate()           Sets the current record's "date" value
 * @method Holiday             setName()           Sets the current record's "name" value
 * 
 * @package    HolidaySharing
 * @subpackage model
 * @author     Cristóbal Medina Moenne
 * @version    SVN: $Id: Builder.php 7490 2014-11-25 10:07:27Z jwage $
 */
abstract class BaseHoliday extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('Holiday');
      
        $this->hasColumn('id', 'integer', 11, array(
            'primary' => true,
            'autoincrement' => true
        ));
        $this->hasColumn('date', 'date', null, array(
            'notnull' => true
        ));
        $this->hasColumn('name', 'string', 100);

        $this->index('id_UNIQUE', array(
            'fields' => array(
                0 => 'id',
            ),
            'type' => 'unique',
        ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();
    }
}