<?php

/**
 * BaseNotification
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $created_at
 * @property string  $message
 * @property integer $notification_type_id
 * 
 * @method integer          getId()                         Returns the current record's "id" value
 * @method timestamp        getCreatedAt()                  Returns the current record's "created_at" value
 * @method string           getMessage()                    Returns the current record's "message" value
 * @method integer          getNotificationTypeId()         Returns the current record's "notification_type_id" value
 *
 * @method Car              setId()                         Sets the current record's "id" value
 * @method Car              setCreatedAt()                  Sets the current record's "created_at" value
 * @method Car              setMessage()                    Sets the current record's "message" value
 * @method Car              setNotificationTypeId()         Sets the current record's "notification_type_id" value
 *
 * @package    Notification
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotification extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Notification');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('message', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('notification_type_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));

        // Indices
        $this->hasColumn('id', 'integer', 4, array(
            'type' => 'integer',
            'primary' => true,
            'autoincrement' => true,
            'length' => 4
        ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();
        
        $this->hasOne('UserNotification', array(
             'local' => 'id',
             'foreign' => 'notification_id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'
        ));

        $this->hasOne('NotificationType', array(
             'local' => 'notification_type_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'
        ));

    }
}