<?php

/**
 * BaseCity
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $State_idt
 * @property string $lng
 * @property string $lat
 * @property State $State
 * @property Doctrine_Collection $Cars
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getStateIdt()  Returns the current record's "State_idt" value
 * @method string              getLng()       Returns the current record's "lng" value
 * @method string              getLat()       Returns the current record's "lat" value
 * @method State               getState()     Returns the current record's "State" value
 * @method Doctrine_Collection getCars()      Returns the current record's "Cars" collection
 * @method City                setId()        Sets the current record's "id" value
 * @method City                setName()      Sets the current record's "name" value
 * @method City                setStateIdt()  Sets the current record's "State_idt" value
 * @method City                setLng()       Sets the current record's "lng" value
 * @method City                setLat()       Sets the current record's "lat" value
 * @method City                setState()     Sets the current record's "State" value
 * @method City                setCars()      Sets the current record's "Cars" collection
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCity extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('City');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('State_idt', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('lng', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('lat', 'string', 45, array(
             'type' => 'string',
             'length' => 45,
             ));


        $this->index('fk_City_State1', array(
             'fields' => 
             array(
              0 => 'State_idt',
             ),
             ));
        $this->index('id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('State', array(
             'local' => 'State_idt',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));

        $this->hasMany('Car as Cars', array(
             'local' => 'id',
             'foreign' => 'City_id'));
    }
}