<?php

/**
 * BaseAvailability
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property timestamp $date_from
 * @property timestamp $date_to
 * @property time $hour_from
 * @property time $hour_to
 * @property integer $day
 * @property integer $Car_id
 * @property Car $Car
 * 
 * @method integer      getId()        Returns the current record's "id" value
 * @method timestamp    getDateFrom()  Returns the current record's "date_from" value
 * @method timestamp    getDateTo()    Returns the current record's "date_to" value
 * @method time         getHourFrom()  Returns the current record's "hour_from" value
 * @method time         getHourTo()    Returns the current record's "hour_to" value
 * @method integer      getDay()       Returns the current record's "day" value
 * @method integer      getCarId()     Returns the current record's "Car_id" value
 * @method Car          getCar()       Returns the current record's "Car" value
 * @method Availability setId()        Sets the current record's "id" value
 * @method Availability setDateFrom()  Sets the current record's "date_from" value
 * @method Availability setDateTo()    Sets the current record's "date_to" value
 * @method Availability setHourFrom()  Sets the current record's "hour_from" value
 * @method Availability setHourTo()    Sets the current record's "hour_to" value
 * @method Availability setDay()       Sets the current record's "day" value
 * @method Availability setCarId()     Sets the current record's "Car_id" value
 * @method Availability setCar()       Sets the current record's "Car" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvailability extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Availability');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('date_from', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('date_to', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('hour_from', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('hour_to', 'time', null, array(
             'type' => 'time',
             ));
        $this->hasColumn('day', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('Car_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             'type' => 'unique',
             ));
        $this->index('fk_Availability_Car1', array(
             'fields' => 
             array(
              0 => 'Car_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Car', array(
             'local' => 'Car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}