<?php

/**
 * BaseDamage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $description
 * @property integer $Car_id
 * @property Car $Car
 * @property float $coordX
 * @property float $coordY
 * @property string $urlFoto
 * @property timestamp $fecha
 * @property boolean $is_deleted
 * 
 * @method integer      getId()          Returns the current record's "id" value
 * @method string       getDescription() Returns the current record's "description" value
 * @method integer      getCarId()       Returns the current record's "Car_id" value
 * @method Car          getCar()         Returns the current record's "Car" value
 * @method float        getCoordX()
 * @method float        getCoordY()
 * @method string       getUrlFoto()
 * @method float        getLat()
 * @method float        getLng()
 * @method timestamp    getFecha()
 * @method bolean       getIsDeleted()         Returns the current record's "is_deleted" value 
 *
 * @method Damage       setId()          Sets the current record's "id" value
 * @method Damage       setDescription() Sets the current record's "description" value
 * @method Damage       setCarId()       Sets the current record's "Car_id" value
 * @method Damage       setCar()         Sets the current record's "Car" value
 * @method float        setCoordX()
 * @method float        setCoordY()
 * @method float        setUrlFoto()
 * @method float        setLat()
 * @method float        setLng()
 * @method timestamp    setFecha()
 * @method UserManagement       setIsDeleted()         Sets the current record's "is_deleted" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDamage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Damages');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'string', 455, array(
             'type' => 'string',
             'length' => 45,
             ));
        $this->hasColumn('Car_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('coordX', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'length' => null,
             ));
        $this->hasColumn('coordY', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'length' => null,
             ));
        $this->hasColumn('urlFoto', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
         $this->hasColumn('lat', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'length' => null,
             ));
        $this->hasColumn('lng', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'length' => null,
             ));            
        $this->hasColumn('fecha', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
            "default" => false
        ));
        $this->index('fk_Damages_Car1', array(
             'fields' => 
             array(
              0 => 'Car_id',
             ),
             ));
        $this->index('id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Car', array(
             'local' => 'Car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}