<?php

/**
 * BaseLiberacionDeposito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $State_idt
 * @property string $lng
 * @property string $lat
 * @property State $State
 * @property Doctrine_Collection $Cars
 * 
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLiberacionDeposito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('LiberacionDeposito');
        $this->hasColumn('id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 11,
             ));
        $this->hasColumn('monto', 'decimal', 10, array(
             'type' => 'decimal',
             'length' => 10,
             'scale' => '2',
             ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }
}