<?php

/**
 * BaseUserMailingConfig
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property User $user
 * @property Mailing $mailing
 * @property boolean $is_subscribed
 * 
 * @method integer              getId()                Returns the current record's "id" value
 * @method User                 getUser()              Returns the current record's "User" value
 * @method Mailing              getMailing()           Returns the current record's "Mailing" value
 * @method boolean              getIsASubscribed()     Returns the current record's "is_subscribed" value
 *
 * @method UserMailingConfig    setId()                Sets the current record's "id" value
 * @method UserMailingConfig    setUser()              Sets the current record's "User" value
 * @method UserMailingConfig    setMailing()           Sets the current record's "Mailing" value
 * @method UserMailingConfig    setIsASubscribed()     Sets the current record's "is_subscribed" value
 * 
 * @package    UserMailingConfigSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserMailingConfig extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('UserMailingConfig');

        $this->hasColumn('id', 'integer', 4, array(
            'type' => 'integer',
            'primary' => true,
            'autoincrement' => true,
            'length' => 4
        ));
        $this->hasColumn('user_id', 'integer', 4, array(
            'type' => 'integer',
            'notnull' => true,
            'length' => 4
        ));
        $this->hasColumn('mailing_id', 'integer', 4, array(
            'type' => 'integer',
            'notnull' => true,
            'length' => 4
        ));
        $this->hasColumn('is_subscribed', 'boolean', false, array(
            'type' => 'boolean',
            'notnull' => true,
            'default' => false
        ));

        $this->index('id_UNIQUE', array(
            'fields' => array(0 => 'id'),
            'type' => 'unique',
        ));

        $this->index('fk_UserMailingConfig_User', array(
            'fields' => array(0 => 'user_id'),
        ));

        $this->index('fk_UserMailingConfig_Mailing', array(
            'fields' => array(0 => 'user_id'),
        ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {
        
        parent::setUp();

        $this->hasOne('User', array(
            'local' => 'user_id',
            'foreign' => 'id',
            'onDelete' => 'no action',
            'onUpdate' => 'no action'
        ));

        $this->hasOne('Mailing', array(
            'local' => 'mailing_id',
            'foreign' => 'id',
            'onDelete' => 'no action',
            'onUpdate' => 'no action'
        ));
    }
}