<?php

/**
 * BaseCarPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $car_id
 * @property string  $name
 * @property boolean $is_processed
 * @property timestamp $created_at
 * @property timestamp $processed_at
 * @property string  $type
 * @property Car     $car
 * 
 * @method integer          getId()                         Returns the current record's "id" value
 * @method integer          getCarId()                      Returns the current record's "car_id" value
 * @method string           getName()                       Returns the current record's "name" value
 * @method boolean          getIsProcessed()                Returns the current record's "is_processed" value
 * @method timestamp        getCreatedAt()                  Returns the current record's "created_at" value
 * @method timestamp        getProcessedAt()                Returns the current record's "processed_at" value
 * @method string           getType()                       Returns the current record's "type" value
 * @method car              getCar()                        Returns the current record's "car" value
 *
 * @method Car              setId()                         Sets the current record's "id" value
 * @method Car              setCarId()                      Sets the current record's "car_id" value
 * @method Car              setName()                       Sets the current record's "name" value
 * @method Car              setÏsProcessed()                Sets the current record's "is_processed" value
 * @method Car              setCreatedAt()                  Sets the current record's "created_at" value
 * @method Car              setProcessedAt()                Sets the current record's "processed_at" value
 * @method Car              setType()                       Sets the current record's "type" value
 * @method Car              setCar()                        Sets the current record's "otros" car
 *
 * @package    CarPhoto
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('CarPhoto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('car_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_processed', 'boolean', null, array(
            'type' => 'boolean'
        ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));

        // Indices
        $this->index('fk_CarPhoto_Car', array(
            'fields' => array(
                0 => 'car_id',
            ),
        ));
        $this->index('id_UNIQUE', array(
            'fields' => array(
                0 => 'id',
            ),
            'type' => 'unique',
        ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();
        
        $this->hasOne('Car', array(
             'local' => 'car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'
        ));

    }
}