<?php

/**
 * BaseReport
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $renter_comment
 * @property string $owner_comment
 * @property integer $Reserve_id
 * @property integer $ReportType_id
 * @property Reserve $Reserve
 * @property ReportType $ReportType
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method string     getRenterComment()  Returns the current record's "renter_comment" value
 * @method string     getOwnerComment()   Returns the current record's "owner_comment" value
 * @method integer    getReserveId()      Returns the current record's "Reserve_id" value
 * @method integer    getReportTypeId()   Returns the current record's "ReportType_id" value
 * @method Reserve    getReserve()        Returns the current record's "Reserve" value
 * @method ReportType getReportType()     Returns the current record's "ReportType" value
 * @method Report     setId()             Sets the current record's "id" value
 * @method Report     setRenterComment()  Sets the current record's "renter_comment" value
 * @method Report     setOwnerComment()   Sets the current record's "owner_comment" value
 * @method Report     setReserveId()      Sets the current record's "Reserve_id" value
 * @method Report     setReportTypeId()   Sets the current record's "ReportType_id" value
 * @method Report     setReserve()        Sets the current record's "Reserve" value
 * @method Report     setReportType()     Sets the current record's "ReportType" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReport extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Report');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('renter_comment', 'string', 90, array(
             'type' => 'string',
             'length' => 90,
             ));
        $this->hasColumn('owner_comment', 'string', 90, array(
             'type' => 'string',
             'length' => 90,
             ));
        $this->hasColumn('Reserve_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('ReportType_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));


        $this->index('fk_Report_Reserve1', array(
             'fields' => 
             array(
              0 => 'Reserve_id',
             ),
             ));
        $this->index('fk_Report_ReportType1', array(
             'fields' => 
             array(
              0 => 'ReportType_id',
             ),
             ));
        $this->index('id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reserve', array(
             'local' => 'Reserve_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));

        $this->hasOne('ReportType', array(
             'local' => 'ReportType_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}