<?php

/**
 * BaseRegion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $natural_order
 * @property boolean $is_active
 * 
 * @method integer       getId()               Returns the current record's "id" value
 * @method boolean       getIsActive()         Returns the current record's "is_active" value
 * @method string        getName()             Returns the current record's "name" value
 * @method integer       getNaturalOrder()     Returns the current record's "natural_order" value
 *
 * @method Region        setId()               Sets the current record's "id" value
 * @method Region        setIsActive()         Sets the current record's "is_active" value
 * @method Region        setName()             Sets the current record's "name" value
 * @method Region        setNaturalOrder()     Sets the current record's "natural_order" value
 * 
 * @package    RegionSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRegion extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('Region');

        $this->hasColumn('id', 'integer', 11, array(
            'primary' => true,
            'autoincrement' => true
        ));
        $this->hasColumn('is_active', 'boolean', null, array(
            'default' => true
        ));
        $this->hasColumn('name', 'string', 255, array(
            'notnull' => true
        ));
        $this->hasColumn('natural_order', 'integer', null, array(
            'notnull' => true
        ));

        $this->index('id_UNIQUE', array(
            'fields' => array(
                0 => 'id',
            ),
            'type' => 'unique',
        ));
        
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();
    }
}