<?php

/**
 * BaseCarAvailability
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property Car $car
 * @property date $day
 * @property boolean $is_deleted
 * @property time $ended_at
 * @property time $started_at
 * 
 * @method integer             getId()             Returns the current record's "id" value
 * @method Car                 getCar()            Returns the current record's "car" value
 * @method date                getDay()            Returns the current record's "day" value
 * @method boolean             getIsDeleted()      Returns the current record's "is_deleted" value
 * @method time                getEndedAt()        Returns the current record's "ended_at" value
 * @method time                getStartedAt()      Returns the current record's "started_at" value
 * 
 * @method CarAvailability     setId()             Sets the current record's "id" value
 * @method CarAvailability     setCar()            Sets the current record's "car" value
 * @method CarAvailability     setDay()            Sets the current record's "checked_at" value
 * @method CarAvailability     setIsDeleted()      Sets the current record's "opened_at" value
 * @method CarAvailability     setEndedAt()        Sets the current record's "ended_at" value
 * @method CarAvailability     setStartedAt()      Sets the current record's "started_at" value
 * 
 * @package    CarAvailabilitySharing
 * @subpackage model
 * @author     Cristóbal Medina Moenne
 * @version    SVN: $Id: Builder.php 7490 2014-11-25 10:07:27Z jwage $
 */
abstract class BaseCarAvailability extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('CarAvailability');
      
        $this->hasColumn('id', 'integer', 11, array(
            'primary' => true,
            'autoincrement' => true
        ));
        $this->hasColumn('car_id', 'integer', 11, array(
            'notnull' => true
        ));
        $this->hasColumn('day', 'date', null, array(
            'notnull' => true
        ));
        $this->hasColumn('is_deleted', 'boolean', null, array(
            "default" => false
        ));
        $this->hasColumn('ended_at', 'time', null, array(
            'notnull' => true
        ));
        $this->hasColumn('started_at', 'time', null, array(
            'notnull' => true
        ));
        
        $this->index('id_UNIQUE', array(
            'fields' => array(
                0 => 'id',
            ),
            'type' => 'unique',
        ));
        $this->index('fk_CarAvailability_Car', array(
            'fields' => array(
                0 => 'car_id',
            ),
        ));

        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        parent::setUp();
        
        $this->hasOne('Car', array(
            'local' => 'car_id',
            'foreign' => 'id',
            'onDelete' => 'no action',
            'onUpdate' => 'no action'
        ));
    }
}