<?php


/**
 * BaseComunas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $codigoInterno
 * @property string $nombre
 * @property integer $padre
 * @property integer $city
 * @property integer $state_id
 * @property Doctrine_Collection $Comunas
 * 
 * @method integer             getCodigoInterno()        Returns the current record's "codigoInterno" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method integer             getPadre()                Returns the current record's "padre" value
 * @method integer             getCodigoBCI()                Returns the current record's "padre" value
 * @method integer             getCity()                Returns the current record's "padre" value
 * @method integer             getStateId()                Returns the current record's "padre" value

 * @method Comunas              setComunas()                 Sets the current record's "Comunas" collection
 * @method Comunas              setCity()                 Sets the current record's "Comunas" collection
 * @method Comunas              setStateId()                 Sets the current record's "Comunas" collection
 * 
 * @package    ComunasSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseComunas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Comunas');
        $this->hasColumn('codigoInterno', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('nombre', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('padre', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('codigo_bci', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('city', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->hasColumn('state_id', 'integer', 11, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 11,
             ));
        $this->index('fk_Comuna_Region1', array(
             'fields' => 
             array(
              0 => 'Padre',
             ),
             ));

        
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }
    public function setUp()
    {
        parent::setUp();

    }
}