<?php

/**
 * BaseCarProximityMetro
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $car_id
 * @property integer $metro_id
 * @property float $long
 * @property Car Car
 * @property Metro Metro
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getCarId()            Returns the current record's "car_id" value
 * @method integer             getMetroId()          Returns the current record's "metro_id" value
 * @method float               getDistance()         Returns the current record's "distance" value
 * @method Car                 getCar()              Returns the current record's "Car" value
 * @method Metro               getMetro()            Returns the current record's "Metro" value
 *
 * @method CarProximityMetro   setCarId()            sets the current record's "car_id" value
 * @method CarProximityMetro   setMetroId()          sets the current record's "metro_id" value
 * @method CarProximityMetro   setDistance()         sets the current record's "distance" value
 * @method CarProximityMetro   setCar()              sets the current record's "Car" value
 * @method CarProximityMetro   setMetro()            sets the current record's "Metro" value
 *
 * @package    CarProximityMetroSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCarProximityMetro extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('CarProximityMetro');
        
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('car_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('metro_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('distance', 'float', 10, array(
             'type' => 'float',
             'length' => 10,
             'scale' => '6',
             ));

        // Indices
        $this->index('fk_CarProximityMetro_Metro', array(
             'fields' => 
             array(
              0 => 'metro_id',
             ),
             ));
        $this->index('fk_CarProximityMetro_Car', array(
             'fields' => 
             array(
              0 => 'car_id',
             ),
             ));
        $this->index('id_UNIQUE', array(
             'fields' => 
             array(
              0 => 'id',
             ),
             'type' => 'unique',
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp() {

        $this->hasOne('Car', array(
             'local' => 'car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'
        ));

        $this->hasOne('Metro', array(
             'local' => 'metro_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'
        ));
    }
}