<?php

/**
 * BaseAvailabilityHasCar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $Availability_id
 * @property integer $Car_id
 * @property Availability $Availability
 * @property Car $Car
 * 
 * @method integer            getAvailabilityId()  Returns the current record's "Availability_id" value
 * @method integer            getCarId()           Returns the current record's "Car_id" value
 * @method Availability       getAvailability()    Returns the current record's "Availability" value
 * @method Car                getCar()             Returns the current record's "Car" value
 * @method AvailabilityHasCar setAvailabilityId()  Sets the current record's "Availability_id" value
 * @method AvailabilityHasCar setCarId()           Sets the current record's "Car_id" value
 * @method AvailabilityHasCar setAvailability()    Sets the current record's "Availability" value
 * @method AvailabilityHasCar setCar()             Sets the current record's "Car" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAvailabilityHasCar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('Availability_has_Car');
        $this->hasColumn('Availability_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('Car_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));


        $this->index('fk_Availability_has_Car_Car1', array(
             'fields' => 
             array(
              0 => 'Car_id',
             ),
             ));
        $this->index('fk_Availability_has_Car_Availability1', array(
             'fields' => 
             array(
              0 => 'Availability_id',
             ),
             ));
        $this->option('charset', 'utf8');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Availability', array(
             'local' => 'Availability_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));

        $this->hasOne('Car', array(
             'local' => 'Car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}