<?php

/**
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePuntajeMapa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('puntaje_mapa');
        $this->hasColumn('car_id', 'integer', 11, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 11,
             ));
        $this->hasColumn('user_id', 'integer', 11, array(
             'type' => 'integer',
             'length' => 11,
             ));
        $this->hasColumn('porcentaje_respuesta', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('asegurado', 'boolean', 1, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
    }
}