<?php

/**
 * BaseOpportunityEmailQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $reserve_id
 * @property integer $car_id
 * @property timestamp $created_at
 * @property timestamp $sended_at
 * @property timestamp $opened_at
 * @property Reserve $Reserve
 * @property Car $Car
 * 
 * @method integer                   getId()            Returns the current record's "id" value
 * @method integer                   getReserveId()     Returns the current record's "reserve_id" value
 * @method integer                   getCarId()         Returns the current record's "car_id" value
 * @method timestamp                 getCreatedAt()     Returns the current record's "created_at" value
 * @method timestamp                 getSendedAt()      Returns the current record's "sended_at" value
 * @method timestamp                 getOpenedAt()      Returns the current record's "opened_at" value
 * @method Reserve                   getReserve()       Returns the current record's "Reserve" value
 * @method Car                       getCar()           Returns the current record's "Car" value
 *
 * @method OpportunityEmailQueue     setId()            Sets the current record's "id" value
 * @method OpportunityEmailQueue     setReserveId()     Sets the current record's "reserve_id" value
 * @method OpportunityEmailQueue     setCarId()         Sets the current record's "car_id" value
 * @method OpportunityEmailQueue     setCreatedAt()     Sets the current record's "created_at" value
 * @method OpportunityEmailQueue     setSendedAt()      Sets the current record's "sended_at" value
 * @method OpportunityEmailQueue     setOpenedAt()      Sets the current record's "opened_at" value
 * @method OpportunityEmailQueue     setReserve()       Sets the current record's "Reserve" value
 * @method OpportunityEmailQueue     setCar()           Sets the current record's "Car" value
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOpportunityEmailQueue extends sfDoctrineRecord {

    public function setTableDefinition() {

        $this->setTableName('OpportunityEmailQueue');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('reserve_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('car_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('sended_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('opened_at', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp() {
        
        parent::setUp();
        
        $this->hasOne('Reserve', array(
             'local' => 'reserve_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
        $this->hasOne('Car', array(
             'local' => 'car_id',
             'foreign' => 'id',
             'onDelete' => 'no action',
             'onUpdate' => 'no action'));
    }
}