<?php

/**
 * AvailabilityHasCarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvailabilityHasCarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvailabilityHasCarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AvailabilityHasCar');
    }
}