<?php

/**
 * AvailabilityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AvailabilityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AvailabilityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Availability');
    }
}