<?php

/**
 * CarType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CarType extends BaseCarType{

	public static function getCarType() {

        $q = Doctrine_Core::getTable("cartype")
            ->createQuery('C')
            ->orderBy('C.name ASC');

        return $q->execute();
    }
}
