<?php

/**
 * CityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('City');
    }
	public function getByStateAndName($id,$name){
	$c = Doctrine_Query::create()
	->from("city")
	->where("state_idt = ?",$id)
	->andWhere("name = ? ",$name);
	return $c->fetchOne();
}
}
