<?php

/**
 * ComunasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ComunasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ComunasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comunas');
    }
}