<?php

/**
 * ConversationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ConversationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ConversationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Conversation');
    }

    public function findConversation($user_id){
      $q = Doctrine_Query::create()
      	->select('*')
        ->from("Conversation c")
        ->where("(c.user_to_id = $user_id OR c.user_from_id = $user_id)");
      return $q->execute();
    }
    public function findConversationWithId($user_id, $id){
      $q = Doctrine_Query::create()
        ->select('*')
        ->from("Conversation c")
        ->where("(c.user_to_id = $user_id OR c.user_from_id = $user_id)")
        ->andWhere("id=$id");
      return $q->execute();
    }
}