<?php

/**
 * Damage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Damage extends BaseDamage
{
	public function getDamageImageS3($size){
	    $Image = Doctrine_Core::getTable("image")->findOneByImageTypeIdAndDamageId(28, $this->getId());
	    if($Image){
	    	return $Image->getImageSize($size);
	    }
	    return null;
  	}

  	public function getImage(){
	    $Image = Doctrine_Core::getTable("image")->findOneByImageTypeIdAndDamageId(28, $this->getId());
	    if($Image){
	    	return $Image;
	    }
	    return null;
  	}
}
