<?php

/**
 * DamageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DamageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DamageTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Damage');
    }
	
	public function findByCar($idcar = '') {
		
		if($idcar) {
			
			try {
				$q = Doctrine_Query::create()
								->from("Damage")
								->where("car_id = ? ",$idcar);
				return  $q->execute();
			}
			catch(Exception $e) { return $e; }
		}
	}
	
	public function findByCarDelete($idcar = '') {
		
		if($idcar) {

			try {
				$q = Doctrine_Query::create()
								->delete()
								->from("Damage")
								->where("car_id = ? ",$idcar)
								->execute();
			}
			catch(Exception $e) { return $e; }
		}
	}
}