<?php

/**
 * LiberacionDepositoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LiberacionDepositoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LiberacionDepositoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LiberacionDeposito');
    }
}
