<?php

/**
 * MailCalificaciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MailCalificaciones extends BaseMailCalificaciones
{
	public function enviarMailCalificaciones(){

        $reserva = Doctrine_Core::getTable("reserve")->findOneById($this->getReserveId());

        //obtiene datos para el mail
        $nameOwner = $reserva->getNameOwner();
        $nameRenter = $reserva->getNameRenter();
        $mailOwner = $reserva->getEmailOwner();
        $mailRenter = $reserva->getEmailRenter();

        //mail propietario
        $mail1 = new Email();
        $mail1->setSubject('Calificaciones');
        $mail1->setBody("<p>Hola $nameOwner:</p><p>Debes dejar un comentario sobre $nameRenter por el arriendo.</p><p>Has click <a href='http://www.arriendas.cl/profile/calificaciones'>aquí</a> para calificarlo.</p>");
        $mail1->setTo($mailOwner);
        $mail1->submit();

        //mail arrendatario
        $mail2 = new Email();
        $mail2->setSubject('Calificaciones');
        $mail2->setBody("<p>Hola $nameRenter:</p><p>Debes dejar un comentario sobre $nameOwner por el arriendo.</p><p>Has click <a href='http://www.arriendas.cl/profile/calificaciones'>aquí</a> para calificarlo.</p>");
        $mail2->setTo($mailRenter);
        $mail2->submit();
	}
}
