<?php

/**
 * Message
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Message extends BaseMessage
{
  public function getDateEs(){
    $date = explode("-",substr($this->getDate(),0,10));
    return $date[2]."/".$date[1]."/".$date[0];
  }
}
