<?php

/**
 * ModelPriceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ModelPriceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ModelPriceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ModelPrice');
    }
}