<?php

/**
 * OportunityQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OportunityQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OportunityQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OportunityQueue');
    }
}