<?php

/**
 * OportunityTaksConfigurationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OportunityTaksConfigurationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OportunityTaksConfigurationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OportunityTaksConfiguration');
    }
}