<?php

/**
 * OportunityEmailQueueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OportunityEmailQueueTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OportunityEmailQueueTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OportunityEmailQueue');
    }
}