<?php

/**
 * Region
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Region extends BaseRegion {

	public static function getRegionsByNaturalOrder() {

		$q = Doctrine_Core::getTable("Region")
            ->createQuery('R')
            ->orderBy('R.natural_order ASC');

        return $q->execute();
	}
}
