<?php

/**
 * RegionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RegionesTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object RegionesTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Regiones');
    }

}