<?php

/**
 * ReportTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReportTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReportTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReportType');
    }
}