<?php

/**
 * ReserveFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReserveFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReserveFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReserveFile');
    }
}