<?php

/**
 * ReserveTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReserveTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ReserveTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Reserve');
    }

    public function getInProgressByUser($user_id) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('user.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.complete = ?', false);
        return $q->execute();
    }

    public function getLastByUser($user_id, $last) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('user.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->orderBy('r.complete asc');
        return $q->execute();
    }

    public function getToConfirmByUser($user_id, $last) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('owner.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', false)
                ->andWhere('r.canceled = ?', false);
        //->orderBy('r.complete asc');
        return $q->execute();
    }

    public function getToConfirmKmsIniciales($user_id) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('owner.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.canceled = ?', false)
                ->andWhere('r.complete = ?', false)
                ->andWhere('r.kminicial != ?', 0)
                ->andWhere('r.ini_km_owner_confirmed = ?', false);

        return $q->execute();
    }

    public function getToConfirmKmsFinales($user_id) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('owner.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.canceled = ?', false)
                ->andWhere('r.complete = ?', false)
                ->andWhere('r.kmfinal != ?', 0)
                ->andWhere('r.end_km_owner_confirmed = ?', false);

        return $q->execute();
    }
    
    public function getToConfirmKmsInicialesUser($user_id) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('r.user_id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.canceled = ?', false)
                ->andWhere('r.complete = ?', false)
                ->andWhere('r.kminicial != ?', 0)
                ->andWhere('r.ini_km_confirmed = ?', false);

        return $q->execute();
    }

    public function getToConfirmKmsFinalesUser($user_id) {
        $q = Doctrine_Query::create()
                ->select('r.id , ca.id idcar , mo.name model,
	  br.name brand, ca.year year,
	  ca.address address, ci.name city,
	  st.name state, co.name country,
	  user.firstname firstname, user.lastname lastname,
	  r.date date'
                )
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('r.user_id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.canceled = ?', false)
                ->andWhere('r.complete = ?', false)
                ->andWhere('r.kmfinal != ?', 0)
                ->andWhere('r.end_km_confirmed = ?', false);

        return $q->execute();
    }
    
    public function countInProgressByUser($user_id) {
        $q = Doctrine_Query::create()
                ->from('Reserve r')
                ->innerJoin('r.Car ca')
                ->innerJoin('ca.Model mo')
                ->innerJoin('ca.User owner')
                ->innerJoin('r.User user')
                ->innerJoin('mo.Brand br')
                ->innerJoin('ca.City ci')
                ->innerJoin('ci.State st')
                ->innerJoin('st.Country co')
                ->where('user.id = ?', $user_id)
                ->andWhere('r.confirmed = ?', true)
                ->andWhere('r.complete = ?', false);
        return $q->count();
    }

}
