<?php

/**
 * ReserveFile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ReserveFile extends BaseReserveFile {
    
    public static $TYPE_IMAGE_LICENCE = "image_licence";
    public static $TYPE_IMAGE_CAR_PANEL_INI = "image_car_panel_initialize";
    public static $TYPE_IMAGE_CAR_PANEL_FIN = "image_car_panel_finalize";
    public static $TYPE_VIDEO_CAR_INI = "video_car_initialize";
    public static $TYPE_VIDEO_CAR_FIN = "video_car_finalize";

    public function getFileName() {
        $filename = explode("/", $this->getPath());
        return $filename[Count($filename) - 1];
    }

}
