<?php

/**
 * User
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class SecurityTokens extends BaseSecurityTokens {

    //Esta funcion genera una firma para una URL dada
    public function generarFirma($url) {
        $parsed_url= parse_url($url);
        $queryString= $parsed_url['query'];
        $temporal= $queryString.$this->getSecret();
        return sha1($temporal);
    }

}
