<?php

/**
 * Transaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Transaction extends BaseTransaction
{
	//retorna la fecha en formato dd/mm/aa
	public function getDateFormato(){
		$date = $this->getDate();
		$date = strtotime($date);
        $fechaFormato = date("d/m/y",$date);
        return $fechaFormato;
	}
	

	public function save(Doctrine_Connection $conn = null)	{

			$reserve = Doctrine_Core::getTable('reserve')->findOneById($this->getReserveId());	
			$car = Doctrine_Core::getTable('car')->findOneById($reserve->getCarId());	
			$user = Doctrine_Core::getTable('user')->findOneById($car->getUserId());	
			$ownerUserId=$user->getId();
			

 	  if ($this->getCompleted() && $this->getCustomerio()<=0)
	  {

			///event to renter
			$session = curl_init();
			$customer_id = 'a_'.$this->getUserId(); // You'll want to set this dynamically to the unique id of the user
			$customerio_url = 'https://track.customer.io/api/v1/customers/'.$customer_id.'/events';
			$site_id = '5b0fca62d5d751d7dcd9';
			$api_key = 'd0cef25ee0d36c4500a9';
			sfContext::getInstance()->getLogger()->err($customerio_url);
			$data = array("name" => "reserva_paga_usuario", "data[id]" => $this->getId());

			curl_setopt($session, CURLOPT_URL, $customerio_url);
			curl_setopt($session, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
			curl_setopt($session, CURLOPT_HEADER, false);
			curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($session, CURLOPT_VERBOSE, 1);
			curl_setopt($session, CURLOPT_CUSTOMREQUEST, 'POST');
			curl_setopt($session, CURLOPT_POSTFIELDS,http_build_query($data));

			curl_setopt($session,CURLOPT_USERPWD,$site_id . ":" . $api_key);

			curl_setopt($session,CURLOPT_SSL_VERIFYPEER,false);

			curl_exec($session);
			curl_close($session);
 
			///event to owner
			$session = curl_init();
			$customer_id = 'a_'.$ownerUserId; // You'll want to set this dynamically to the unique id of the user
			$customerio_url = 'https://track.customer.io/api/v1/customers/'.$customer_id.'/events';
			$site_id = '5b0fca62d5d751d7dcd9';
			$api_key = 'd0cef25ee0d36c4500a9';
			sfContext::getInstance()->getLogger()->err($customerio_url);
			$data = array("name" => "reserva_paga_dueno", "data[id]" => $this->getId());

			curl_setopt($session, CURLOPT_URL, $customerio_url);
			curl_setopt($session, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
			curl_setopt($session, CURLOPT_HEADER, false);
			curl_setopt($session, CURLOPT_RETURNTRANSFER, true);
			curl_setopt($session, CURLOPT_VERBOSE, 1);
			curl_setopt($session, CURLOPT_CUSTOMREQUEST, 'POST');
			curl_setopt($session, CURLOPT_POSTFIELDS,http_build_query($data));

			curl_setopt($session,CURLOPT_USERPWD,$site_id . ":" . $api_key);

			curl_setopt($session,CURLOPT_SSL_VERIFYPEER,false);

			curl_exec($session);
			curl_close($session);
  
	  
		}	  
	  
	  return parent::save($conn);
	}

	
	}

