<?php

/**
 * Transaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    CarSharing
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Transaction extends BaseTransaction
{
	//retorna la fecha en formato dd/mm/aa
	public function getDateFormato(){
		$date = $this->getDate();
		$date = strtotime($date);
        $fechaFormato = date("d/m/y",$date);
        return $fechaFormato;
	}
	
}
