<?php

/**
 * UserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object UserTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('User');
    }
    
    /**
     * Get ip corresponds to a propietario user.
     * @param type $ip_number
     * @return User
     */
    public function getPropietarioByIp($ip_number, $is_propietario = false) {
        $q = $this->getInstance()->createQuery("u")
                ->where("u.tracked_ips LIKE ?", "%$ip_number%")
                ->andWhere("u.propietario = ?", $is_propietario);
        return $q->execute();
    }

}
