<?php

/**
 * UserAdminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserAdminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UserAdminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UserAdmin');
    }
}