<div class="content prv">
  <div class="container">
    <div class="row">
      <div class="grid_12">
        <h2 class="mb1">privacy policy</h2>
        <div class="text1 col2">Consequat ante Lorem ipsum dolorSit ametConsetetuer Adipiscing elitPellentesqu sedDolorAliquam congueFermentum nislM auris accumsan Nulla vel diam Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
        <p>Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.Lorem ips um dolor sit amet, consectetur adipiscing elit. Cras eros nulla, porta ut est in, cursus egestas velit. Cras quis bibendum odio, in condimentum ante. Aliquam gravida mauris sed imperdiet porttitor. Vestibulum feugiat nulla id massa porta varius. Phasellus dui sem volutpat quis dignissi mvitae, auctor quis nunc. Duis malesuada, elit nec faucibus feugiat, ligula arcu porta erat, quis molestie justo nulla ac mi. Ut ultricies ante et nisl porttitor laoreet eget vitae turpis. Duis nec enim metus. Vestibulum id eros lobortis, accumsan orci lobortis, pretium felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cureget urna condimentumLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dolor fringilla, mattis arcu vel, cursus risus. Duis imperdiet, eros sed ultrices auctor, augue est tincidunt erat, sed porta dui nisi eu urna. Integer et vulputate enim. Nulla in velit auctor, tincidunt ligula quis, venenatis odio. </p>
        <div class="text1 col2">Consequat ante Lorem ipsum dolorSit ametConsetetuer Adipiscing elitPellentesqu sedDolorAliquam congueFermentum nislM auris accumsan Nulla vel diam Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
        <p>Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.Lorem ips um dolor sit amet, consectetur adipiscing elit. Cras eros nulla, porta ut est in, cursus egestas velit. Cras quis bibendum odio, in condimentum ante. Aliquam gravida mauris sed imperdiet porttitor. Vestibulum feugiat nulla id massa porta varius. Phasellus dui sem volutpat quis dignissi mvitae, auctor quis nunc. Duis malesuada, elit nec faucibus feugiat, ligula arcu porta erat, quis molestie justo nulla ac mi. Ut ultricies ante et nisl porttitor laoreet eget vitae turpis. Duis nec enim metus. Vestibulum id eros lobortis, accumsan orci lobortis, pretium felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cureget urna condimentumLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dolor fringilla, mattis arcu vel, cursus risus. Duis imperdiet, eros sed ultrices auctor, augue est tincidunt erat, sed porta dui nisi eu urna. Integer et vulputate enim. Nulla in velit auctor, tincidunt ligula quis, venenatis odio. </p>
        <div class="text1 col2">Consequat ante Lorem ipsum dolorSit ametConsetetuer Adipiscing elitPellentesqu sedDolorAliquam congueFermentum nislM auris accumsan Nulla vel diam Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
        <p>Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.Lorem ips um dolor sit amet, consectetur adipiscing elit. Cras eros nulla, porta ut est in, cursus egestas velit. Cras quis bibendum odio, in condimentum ante. Aliquam gravida mauris sed imperdiet porttitor. Vestibulum feugiat nulla id massa porta varius. Phasellus dui sem volutpat quis dignissi mvitae, auctor quis nunc. Duis malesuada, elit nec faucibus feugiat, ligula arcu porta erat, quis molestie justo nulla ac mi. Ut ultricies ante et nisl porttitor laoreet eget vitae turpis. Duis nec enim metus. Vestibulum id eros lobortis, accumsan orci lobortis, pretium felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cureget urna condimentumLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dolor fringilla, mattis arcu vel, cursus risus. Duis imperdiet, eros sed ultrices auctor, augue est tincidunt erat, sed porta dui nisi eu urna. Integer et vulputate enim. Nulla in velit auctor, tincidunt ligula quis, venenatis odio. </p>
        <div class="text1 col2">Consequat ante Lorem ipsum dolorSit ametConsetetuer Adipiscing elitPellentesqu sedDolorAliquam congueFermentum nislM auris accumsan Nulla vel diam Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
        <p>Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.Lorem ips um dolor sit amet, consectetur adipiscing elit. Cras eros nulla, porta ut est in, cursus egestas velit. Cras quis bibendum odio, in condimentum ante. Aliquam gravida mauris sed imperdiet porttitor. Vestibulum feugiat nulla id massa porta varius. Phasellus dui sem volutpat quis dignissi mvitae, auctor quis nunc. Duis malesuada, elit nec faucibus feugiat, ligula arcu porta erat, quis molestie justo nulla ac mi. Ut ultricies ante et nisl porttitor laoreet eget vitae turpis. Duis nec enim metus. Vestibulum id eros lobortis, accumsan orci lobortis, pretium felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cureget urna condimentumLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dolor fringilla, mattis arcu vel, cursus risus. Duis imperdiet, eros sed ultrices auctor, augue est tincidunt erat, sed porta dui nisi eu urna. Integer et vulputate enim. Nulla in velit auctor, tincidunt ligula quis, venenatis odio. </p>
        <div class="text1 col2">Consequat ante Lorem ipsum dolorSit ametConsetetuer Adipiscing elitPellentesqu sedDolorAliquam congueFermentum nislM auris accumsan Nulla vel diam Lorem ipsum dolor sit amet, consectetur adipiscing elit</div>
        <p>Sed in lacus ut enim adipiscing aliquet. Nulla venenatis. In pede mi, aliquet sit amet, euismod in, auctor ut, ligula. Aliquam dapibus tincidunt metus. Praesent justo dolor, lobortis quis, lobortis dignissim, pulvinar ac, lorem. Vestibulum sed ante. Donec sagittis euismod purus.Lorem ips um dolor sit amet, consectetur adipiscing elit. Cras eros nulla, porta ut est in, cursus egestas velit. Cras quis bibendum odio, in condimentum ante. Aliquam gravida mauris sed imperdiet porttitor. Vestibulum feugiat nulla id massa porta varius. Phasellus dui sem volutpat quis dignissi mvitae, auctor quis nunc. Duis malesuada, elit nec faucibus feugiat, ligula arcu porta erat, quis molestie justo nulla ac mi. Ut ultricies ante et nisl porttitor laoreet eget vitae turpis. Duis nec enim metus. Vestibulum id eros lobortis, accumsan orci lobortis, pretium felis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Cureget urna condimentumLorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu dolor fringilla, mattis arcu vel, cursus risus. Duis imperdiet, eros sed ultrices auctor, augue est tincidunt erat, sed porta dui nisi eu urna. Integer et vulputate enim. Nulla in velit auctor, tincidunt ligula quis, venenatis odio. </p>
        <a href="#" class="col3 td">soporte@arriendas.cl </a>
      </div>
    </div>
  </div>
</div>
<script>
$(document).ready(function(){    
      $(".sf-menu").find(".current").removeClass("current"); 
      $(".sf-menu li:nth-child(4)").addClass("current");
});
</script>