<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/21 19:52:29

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1;dbname=arriendas',
  'username' => 'usuario',
  'password' => 'pass',
  'name' => 'doctrine',
)),);
