<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/08/22 22:49:57

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=test',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
