<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/21 19:51:36
sfConfig::add(array(
  'app_video_width' => '280px',
  'app_video_height' => '210px',
  'app_video_autoplay' => false,
  'app_video_autobuffering' => true,
  'app_video_hideDelay' => 100,
  'app_url' => 'http://test.intothewhitebox.com/girai/',
));
